import Link from 'next/link'
import {notFound} from 'next/navigation'
import {ArrowUpRight} from 'lucide-react'
import SiteHeader from '../../../components/SiteHeader'
import BrandLogo from '../../../components/BrandLogo'
import {categories,getService} from '../../data'

const categoryMeta:{[key:string]:{position:string;fee:string;work:[string,string,string][];metrics:[string,string][]}}={
 brand:{position:'Build the meaning, position and visual language before the world sees the brand.',fee:'₹75K–₹3L+',work:[['WHIFFF','Brand identity / Digital','/projects/whifff'],['Lucky Paul Photography','Brand / Photography','/projects/lucky-paul'],['PawPerity','Packaging / Brand','/projects/pawperity']],metrics:[['+46%','Illustrative recognition lift'],['3.4×','Illustrative asset usage'],['70+','Illustrative reusable assets']]},
 digital:{position:'Turn the brand into digital experiences people can understand, navigate and remember.',fee:'₹1L–₹4L+',work:[['WHIFFF','Digital / Brand','/projects/whifff'],['The Minimical & Co.','Studio / Digital','/projects/minimical'],['Enchanted Vows','Identity / Digital','/projects/enchanted-vows']],metrics:[['+31%','Illustrative conversion lift'],['2.7×','Illustrative engaged sessions'],['-24%','Illustrative bounce reduction']]},
 campaigns:{position:'Find the central idea, then build the communication system that lets it travel.',fee:'₹75K–₹4L+',work:[['Health Seva','Campaign / Communication','/projects/health-seva'],['Jaano Junction','Event / Identity','/projects/jaano-junction'],['PawPerity','Brand / Campaign','/projects/pawperity']],metrics:[['2.8×','Illustrative campaign reach'],['+52%','Illustrative share of voice'],['+41%','Illustrative saves / shares']]},
 production:{position:'Make the idea tangible through photography, film, motion, editing and finishing.',fee:'₹50K–₹6L+',work:[['Enchanted Vows','Film / Photography','/projects/enchanted-vows'],['Lucky Paul Photography','Photography','/projects/lucky-paul'],['WHIFFF','Visual production / Brand','/projects/whifff']],metrics:[['2.6×','Illustrative completion rate'],['+47%','Illustrative film enquiries'],['2.2×','Illustrative content reuse']]}
}

export function generateStaticParams(){return categories.map(c=>({slug:c.slug}))}
export default async function CategoryPage({params}:{params:Promise<{slug:string}>}){
 const {slug}=await params;const c=categories.find(x=>x.slug===slug);if(!c)notFound();const items=c.services.map(getService).filter(Boolean);const meta=categoryMeta[slug]
 return <main className="categoryDetail innerPage"><SiteHeader/>
 <section className="categoryHero"><div><span>Program / {c.name}</span><h1>{c.name}<br/><i>as a discipline.</i></h1><p>{meta.position}</p></div><div className="categoryHeroAside"><span>{String(items.length).padStart(2,'0')} specialist services</span><span>Typical range<strong>{meta.fee}</strong></span><Link href={`/contact?category=${slug}`}>Build a scope <ArrowUpRight size={16}/></Link></div></section>
 <section className="categoryServices"><div className="sectionIntro"><span>{c.name} / Services</span><h2>Two specialist entry points.<br/><i>One connected practice.</i></h2></div><div className="categoryServiceList">{items.map((s,i)=><Link href={`/services/${s!.slug}`} key={s!.slug}><span>{String(i+1).padStart(2,'0')}</span><div><strong>{s!.name}</strong><p>{s!.tagline}</p><small>{s!.fee}</small></div><ArrowUpRight size={20}/></Link>)}</div></section>
 <section className="categoryWork"><div className="sectionIntro"><span>Selected work / {c.name}</span><h2>Where the discipline<br/><i>meets the real world.</i></h2></div><div className="categoryWorkGrid">{meta.work.map(([name,type,href],i)=><Link href={href} key={name}><span>{String(i+1).padStart(2,'0')}</span><div><strong>{name}</strong><small>{type}</small></div><ArrowUpRight size={18}/></Link>)}</div></section>
 <section className="categoryFramework"><div><span>Scope / Engagement model</span><h2>Built around<br/><i>the problem.</i></h2></div><div className="frameworkSteps"><article><small>01</small><strong>Brief</strong><p>We understand the business, audience, ambition and existing conditions before recommending a scope.</p></article><article><small>02</small><strong>Direction</strong><p>Strategy and creative direction establish the route before production expands the work.</p></article><article><small>03</small><strong>Build</strong><p>The selected specialists work as one team, with fewer handoffs and a clear owner for the idea.</p></article><article><small>04</small><strong>Launch</strong><p>Final systems, files, production and rollout support are shaped for real use after delivery.</p></article></div></section>
 <section className="categoryProof"><div className="sectionIntro"><span>Performance / Editorial placeholders</span><h2>Numbers with<br/><i>some context.</i></h2></div><p className="categoryProofLead">Temporary sample figures are included to complete the commercial structure. Replace them with approved results when the real project data is supplied.</p><div className="metricGrid">{meta.metrics.map(([n,t])=><article key={t}><strong>{n}</strong><b>{t}</b><span>Illustrative placeholder</span></article>)}</div></section>
 <section className="categoryEnquiry"><div><span>Project enquiry / {c.name}</span><h2>Have a brief?<br/><i>Start here.</i></h2><p>Tell us what is changing, what you need made, when it needs to happen and the investment range you have in mind.</p><div className="categoryContactDetails"><span>contact@minimical.online</span><span>+91 87095 39814</span><span>Patna / India / Worldwide</span></div></div><form action="mailto:contact@minimical.online" method="post" encType="text/plain"><input name="name" placeholder="Name" required/><input name="email" type="email" placeholder="Email" required/><input name="company" placeholder="Company / Brand"/><input name="timeline" placeholder="Timeline / launch date"/><input name="budget" placeholder={`Budget / ${meta.fee}`} /><textarea name="brief" placeholder={`Tell us about your ${c.name.toLowerCase()} requirement`} rows={6} required/><button type="submit">Send {c.name} enquiry <ArrowUpRight size={16}/></button></form></section>
 <section className="categoryNavigation"><Link href="/services">← All programs</Link>{categories.filter(x=>x.slug!==c.slug).map(x=><Link href={`/services/category/${x.slug}`} key={x.slug}>{x.name} ↗</Link>)}</section>
 <footer><div className="footerBrand"><BrandLogo/></div><Link href="/services">All programs ↗</Link><Link href="/projects">Work ↗</Link><Link href="/about">Studio ↗</Link><Link href="/contact">Contact ↗</Link><span>Patna / India / Worldwide</span></footer></main>
}