import Link from 'next/link'
import { notFound } from 'next/navigation'
import { ArrowLeft, ArrowUpRight } from 'lucide-react'
import BrandLogo from '../../components/BrandLogo'
import SiteHeader from '../../components/SiteHeader'
import { projects, projectBySlug } from '../data'

type Props={params:Promise<{slug:string}>}
export function generateStaticParams(){return projects.map(project=>({slug:project.slug}))}

export default async function ProjectPage({params}:Props){const {slug}=await params;const project=projectBySlug[slug];if(!project)notFound();const index=projects.findIndex(item=>item.slug===slug);const next=projects[(index+1)%projects.length];return <main className="casePage"><SiteHeader/><section className={`caseHero ${project.className}`}><div className="caseHeroTop"><span>{project.n} / {project.year}</span><span>{project.category}</span></div><div className="caseMark">{project.mark}</div><div className="caseHeroBottom"><h1>{project.name}</h1><p>{project.intro}</p></div></section><section className="caseMeta"><div><small>Client / project</small><strong>{project.name}</strong></div><div><small>Discipline</small><strong>{project.category}</strong></div><div><small>Role</small><strong>Strategy · Design · Direction</strong></div></section><section className="caseNarrative"><div className="caseLabel">01 / The challenge</div><div><h2>The question<br/><i>behind the brief.</i></h2><p>{project.challenge}</p></div></section><section className="caseNarrative reverse"><div className="caseLabel">02 / The idea</div><div><h2>Start with<br/><i>the thought.</i></h2><p>{project.idea}</p></div></section><section className={`caseVisual ${project.className}`}><span>{project.name.toUpperCase()}</span><strong>{project.mark}</strong><small>IDENTITY / SYSTEM / APPLICATION</small></section><section className="caseNarrative"><div className="caseLabel">03 / The system</div><div><h2>Build something<br/><i>that can live.</i></h2><p>{project.system}</p><div className="deliverables">{project.deliverables.map((item,i)=><span key={item}><b>{String(i+1).padStart(2,'0')}</b>{item}</span>)}</div></div></section><section className="caseOutcome"><small>04 / The outcome</small><h2>{project.outcome}</h2></section><section className="caseProof"><div><small>05 / Growth signal</small><h2>What should<br/><i>move?</i></h2></div><div><p>Use this space for the verified business result once the project has enough live data.</p><div className="metricSlots"><span>Awareness / reach</span><span>Enquiries / conversion</span><span>Retention / repeat</span></div></div></section><section className="caseProof testimonial"><div><small>06 / Client note</small><h2>The work,<br/><i>in their words.</i></h2></div><div><blockquote>“Representative feedback can live here once the client approves the exact wording for publication.”</blockquote><p>Editorial placeholder, ready to replace with a verified quote, name and role.</p></div></section><section className="nextProject"><div><small>Next project</small><h2>{next.name}</h2></div><Link href={`/projects/${next.slug}`}><ArrowUpRight size={24}/></Link></section><footer><div className="footerBrand"><BrandLogo/></div><Link href="/projects"><ArrowLeft size={14}/> All projects</Link><span>Patna, India</span></footer></main>}
