export type ServiceItem={slug:string;name:string;category:string;tagline:string;description:string;fee:string;scope:string[];deliverables:string[];metrics:[string,string][];reviews:[string,string][]}
export const categories=[
{slug:'brand',name:'Brand',intro:'Build a brand people can recognise, understand and remember.',services:['brand-strategy','brand-identity']},
{slug:'digital',name:'Digital',intro:'Turn the brand into digital experiences that are clear, useful and unmistakably yours.',services:['web-design','digital-experiences']},
{slug:'campaigns',name:'Campaigns',intro:'Create ideas and communication systems built to launch, travel and stay relevant.',services:['campaign-strategy','content-campaigns']},
{slug:'production',name:'Production',intro:'Make the idea real through photography, film, motion and post production.',services:['motion-film','photography']},]
const base={
'brand-strategy':['Brand Strategy','Brand','Find the position before designing the expression.','A strategic foundation for brands that need a sharper reason to exist, a clearer audience and a point of view the whole organisation can use.','₹75K–₹1.5L',['Discovery and stakeholder conversations','Audience and competitive mapping','Positioning and value proposition','Brand architecture and naming direction','Messaging hierarchy and creative territory'],['Strategy workshop','Positioning framework','Audience / competitor map','Messaging framework','Creative direction'],[['+34%','Illustrative aided awareness lift'],['2.1×','Illustrative qualified enquiry growth'],['18%','Illustrative message recall improvement']],['“The strategy finally gave the team one language for what we were trying to build.”','“It changed the brief from make it look better to make the proposition clearer.”']],
'brand-identity':['Brand Identity','Brand','Give the idea a visual system with a point of view.','A complete identity system that turns positioning into a recognisable visual language across physical and digital touchpoints.','₹1L–₹3L+',['Identity audit or strategic handoff','Logo and mark direction','Typography and colour system','Art direction and graphic language','Guidelines and rollout planning'],['Primary identity','Logo suite','Typography / colour system','Graphic assets','Brand guidelines','Launch-ready templates'],[['3.4×','Illustrative brand asset usage'],['+46%','Illustrative recognition improvement'],['70+','Illustrative reusable brand assets']],['“We stopped improvising every time the brand appeared somewhere new.”','“It feels like one brand now, not fifty disconnected executions.”']],
'web-design':['Web Design','Digital','Make the website the clearest expression of the brand.','Editorial, conversion-aware websites designed around content hierarchy, interaction and a distinctive visual system.','₹1.25L–₹4L+',['Information architecture','UX and content structure','Responsive visual design','Interaction and motion direction','Development handoff or implementation'],['Site architecture','Wireframes','Visual design','Responsive screens','Interaction specification','Launch support'],[['+31%','Illustrative conversion improvement'],['2.7×','Illustrative engaged-session growth'],['-24%','Illustrative bounce-rate reduction']],['“The website finally feels like the brand rather than a separate marketing tool.”','“People understood what we do faster and the enquiry quality improved.”']],
'digital-experiences':['Digital Experiences','Digital','Design systems that make digital feel considered.','Campaign microsites, portfolios, product surfaces and interactive experiences where structure, content and motion work as one.','₹1L–₹3.5L+',['Experience concept','User flows and journey mapping','Interface system','Interaction design','Prototype and testing'],['Experience map','UI system','Interactive prototype','Responsive layouts','Motion / interaction notes'],[['+38%','Illustrative task completion'],['2.4×','Illustrative interaction depth'],['-19%','Illustrative time to key action']],['“The experience gives the audience something to discover instead of another page to scroll.”','“It feels premium because every interaction has a reason.”']],
'campaign-strategy':['Campaign Strategy','Campaigns','Find the idea people can actually remember.','Campaign thinking from cultural insight to platform, message and launch architecture, giving content a central idea instead of a pile of posts.','₹75K–₹2L',['Brief and audience definition','Cultural / competitive research','Campaign platform','Message architecture','Launch and channel strategy'],['Campaign insight','Big idea / platform','Creative territories','Channel framework','Launch roadmap'],[['2.8×','Illustrative campaign reach'],['+52%','Illustrative share of voice'],['+29%','Illustrative qualified traffic']],['“The campaign stopped sounding like advertising and started sounding like the brand.”','“We had an idea people could repeat, not just an artwork people could like.”']],
'content-campaigns':['Content Campaigns','Campaigns','Build a content system that keeps the idea moving.','Art direction and production planning for social, launch and campaign content, from hero assets to repeatable content formats.','₹1L–₹4L+',['Content strategy','Creative direction','Shot / production planning','Hero and supporting asset system','Editing and delivery'],['Content concepts','Moodboards','Shot lists','Hero assets','Social / digital cutdowns','Content toolkit'],[['3.1×','Illustrative content reach'],['+41%','Illustrative saves / shares'],['64%','Illustrative repeat audience rate']],['“The system made six weeks of content feel like one campaign.”','“Every asset feels related without becoming repetitive.”']],
'motion-film':['Motion / Film','Production','Shape the story from first frame to final delivery.','Cinematography, motion, editing and post production for brand films, commercials, launch films, social stories and identity motion.','₹1.5L–₹6L+',['Creative treatment','Pre-production and scheduling','Cinematography / motion','Editing and sound direction','Colour and final delivery'],['Treatment','Storyboard / shot list','Production','Edit','Motion graphics','Colour / finishing','Master and cutdowns'],[['2.6×','Illustrative completion rate'],['+47%','Illustrative film-driven enquiries'],['78%','Illustrative full-view rate']],['“The film understood the mood of the brand without explaining it to death.”','“It gave the launch a visual world we could keep building from.”']],
'photography':['Photography','Production','Make the frame belong to the brand.','Campaign, product, portrait, lifestyle and editorial photography planned around the identity, audience and intended use of the images.','₹50K–₹3L+',['Creative direction','Location / casting direction','Pre-production','Shoot day(s)','Selection, retouching and delivery'],['Creative treatment','Shot list','Production direction','Final selects','Retouched masters','Digital crops / formats'],[['+36%','Illustrative product engagement'],['2.2×','Illustrative content reuse'],['+44%','Illustrative campaign saves']],['“The images finally look like they came from the same world as the brand.”','“We got a library we could actually use, not just a beautiful shoot.”']]}}
export const services:ServiceItem[]=Object.entries(base).map(([slug,v])=>({slug,name:v[0],category:v[1],tagline:v[2],description:v[3],fee:v[4],scope:v[5],deliverables:v[6],metrics:v[7],reviews:[['Client / selected engagement',v[8][0]],['Marketing / selected engagement',v[8][1]]]}))
export function getService(slug:string){return services.find(s=>s.slug===slug)}
export function getCategory(slug:string){return categories.find(c=>c.slug===slug)}
