export type ServiceItem={slug:string;name:string;category:string;tagline:string;description:string;fee:string;scope:string[];deliverables:string[];metrics:[string,string][];reviews:[string,string][]}
type RawService={name:string;category:string;tagline:string;description:string;fee:string;scope:string[];deliverables:string[];metrics:[string,string][];quotes:[string,string]}
export const categories=[
 {slug:'brand',name:'Brand',intro:'Build the meaning, position and visual language before the world sees the brand.',services:['brand-strategy','brand-identity']},
 {slug:'digital',name:'Digital',intro:'Turn the brand into digital experiences people can understand, navigate and remember.',services:['web-design','digital-experiences']},
 {slug:'campaigns',name:'Campaigns',intro:'Find the central idea, then build the communication system that lets it travel.',services:['campaign-strategy','content-campaigns']},
 {slug:'production',name:'Production',intro:'Make the idea tangible through photography, film, motion, editing and finishing.',services:['motion-film','photography']},
]
export const serviceContent:Record<string,RawService>={
 'brand-strategy':{name:'Brand Strategy',category:'Brand',tagline:'Find the position before designing the expression.',description:'A strategic foundation for brands that need a sharper reason to exist, a clearer audience and a point of view the whole organisation can use.',fee:'₹75K–₹1.5L',scope:['Discovery and stakeholder conversations','Audience and competitive mapping','Positioning and value proposition','Brand architecture and naming direction','Messaging hierarchy and creative territory'],deliverables:['Strategy workshop','Positioning framework','Audience / competitor map','Messaging framework','Creative direction'],metrics:[['+34%','Illustrative aided awareness lift'],['2.1×','Illustrative qualified enquiry growth'],['18%','Illustrative message recall improvement']],quotes:['“The strategy finally gave the team one language for what we were trying to build.”','“It changed the brief from make it look better to make the proposition clearer.”']},
 'brand-identity':{name:'Brand Identity',category:'Brand',tagline:'Give the idea a visual system with a point of view.',description:'A complete identity system that turns positioning into a recognisable visual language across physical and digital touchpoints.',fee:'₹1L–₹3L+',scope:['Identity audit or strategic handoff','Logo and mark direction','Typography and colour system','Art direction and graphic language','Guidelines and rollout planning'],deliverables:['Primary identity','Logo suite','Typography / colour system','Graphic assets','Brand guidelines','Launch-ready templates'],metrics:[['3.4×','Illustrative brand asset usage'],['+46%','Illustrative recognition improvement'],['70+','Illustrative reusable brand assets']],quotes:['“We stopped improvising every time the brand appeared somewhere new.”','“It feels like one brand now, not fifty disconnected executions.”']},
 'web-design':{name:'Web Design',category:'Digital',tagline:'Make the website the clearest expression of the brand.',description:'Editorial, conversion-aware websites designed around content hierarchy, interaction and a distinctive visual system.',fee:'₹1.25L–₹4L+',scope:['Information architecture','UX and content structure','Responsive visual design','Interaction and motion direction','Development handoff or implementation'],deliverables:['Site architecture','Wireframes','Visual design','Responsive screens','Interaction specification','Launch support'],metrics:[['+31%','Illustrative conversion improvement'],['2.7×','Illustrative engaged-session growth'],['-24%','Illustrative bounce-rate reduction']],quotes:['“The website finally feels like the brand rather than a separate marketing tool.”','“People understood what we do faster and the enquiry quality improved.”']},
 'digital-experiences':{name:'Digital Experiences',category:'Digital',tagline:'Design systems that make digital feel considered.',description:'Campaign microsites, portfolios, product surfaces and interactive experiences where structure, content and motion work as one.',fee:'₹1L–₹3.5L+',scope:['Experience concept','User flows and journey mapping','Interface system','Interaction design','Prototype and testing'],deliverables:['Experience map','UI system','Interactive prototype','Responsive layouts','Motion / interaction notes'],metrics:[['+38%','Illustrative task completion'],['2.4×','Illustrative interaction depth'],['-19%','Illustrative time to key action']],quotes:['“The experience gives the audience something to discover instead of another page to scroll.”','“It feels premium because every interaction has a reason.”']},
 'campaign-strategy':{name:'Campaign Strategy',category:'Campaigns',tagline:'Find the idea people can actually remember.',description:'Campaign thinking from cultural insight to platform, message and launch architecture, giving content a central idea instead of a pile of posts.',fee:'₹75K–₹2L',scope:['Brief and audience definition','Cultural / competitive research','Campaign platform','Message architecture','Launch and channel strategy'],deliverables:['Campaign insight','Big idea / platform','Creative territories','Channel framework','Launch roadmap'],metrics:[['2.8×','Illustrative campaign reach'],['+52%','Illustrative share of voice'],['+29%','Illustrative qualified traffic']],quotes:['“The campaign stopped sounding like advertising and started sounding like the brand.”','“We had an idea people could repeat, not just an artwork people could like.”']},
 'content-campaigns':{name:'Content Campaigns',category:'Campaigns',tagline:'Build a content system that keeps the idea moving.',description:'Art direction and production planning for social, launch and campaign content, from hero assets to repeatable content formats.',fee:'₹1L–₹4L+',scope:['Content strategy','Creative direction','Shot / production planning','Hero and supporting asset system','Editing and delivery'],deliverables:['Content concepts','Moodboards','Shot lists','Hero assets','Social / digital cutdowns','Content toolkit'],metrics:[['3.1×','Illustrative content reach'],['+41%','Illustrative saves / shares'],['64%','Illustrative repeat audience rate']],quotes:['“The system made six weeks of content feel like one campaign.”','“Every asset feels related without becoming repetitive.”']},
 'motion-film':{name:'Motion / Film',category:'Production',tagline:'Shape the story from first frame to final delivery.',description:'Cinematography, motion, editing and post production for brand films, commercials, launch films, social stories and identity motion.',fee:'₹1.5L–₹6L+',scope:['Creative treatment','Pre-production and scheduling','Cinematography / motion','Editing and sound direction','Colour and final delivery'],deliverables:['Treatment','Storyboard / shot list','Production','Edit','Motion graphics','Colour / finishing','Master and cutdowns'],metrics:[['2.6×','Illustrative completion rate'],['+47%','Illustrative film-driven enquiries'],['78%','Illustrative full-view rate']],quotes:['“The film understood the mood of the brand without explaining it to death.”','“It gave the launch a visual world we could keep building from.”']},
 'photography':{name:'Photography',category:'Production',tagline:'Make the frame belong to the brand.',description:'Campaign, product, portrait, lifestyle and editorial photography planned around the identity, audience and intended use of the images.',fee:'₹50K–₹3L+',scope:['Creative direction','Location / casting direction','Pre-production','Shoot day(s)','Selection, retouching and delivery'],deliverables:['Creative treatment','Shot list','Production direction','Final selects','Retouched masters','Digital crops / formats'],metrics:[['+36%','Illustrative product engagement'],['2.2×','Illustrative content reuse'],['+44%','Illustrative campaign saves']],quotes:['“The images finally look like they came from the same world as the brand.”','“We got a library we could actually use, not just a beautiful shoot.”']},
}
export const services:ServiceItem[]=Object.entries(serviceContent).map(([slug,v])=>({slug,...v,reviews:[['Client / selected engagement',v.quotes[0]],['Marketing / selected engagement',v.quotes[1]]]}))
export function getService(slug:string){return services.find(s=>s.slug===slug)}
export function getCategory(slug:string){return categories.find(c=>c.slug===slug)}
