import Link from 'next/link'
import {ArrowUpRight} from 'lucide-react'
import BrandLogo from '../components/BrandLogo'
import SiteHeader from '../components/SiteHeader'
const services=[['01','Brand Strategy','Positioning, naming, brand architecture and creative direction that give a business a clear place in the world.'],['02','Brand Identity','Logos, typography, colour, art direction and complete visual systems designed to be recognisable and usable.'],['03','Digital Design','Websites, portfolios, campaigns and interfaces where structure, interaction and visual language work together.'],['04','Campaigns & Content','Campaign concepts, art direction, launch systems, social content and communication designed to move with the brand.'],['05','Motion / Film','Motion systems, title design, cinematography, editing and post from the first frame to final delivery.'],['06','Photography','Campaign, product, portrait, lifestyle and editorial imagery shaped around the identity of the work.']]
const pricing=[['01','Focused','₹75K–₹1.5L','A defined problem, one discipline, a clear deliverable.'],['02','Integrated','₹1.5L–₹4L','Strategy plus identity, digital or campaign work in one connected engagement.'],['03','End to end','₹4L+','A larger brand or launch system spanning thinking, design and production.']]
const outcomes=[['Clarity','Positioning, message hierarchy, offer and audience'],['Consistency','Identity rules that survive across every touchpoint'],['Conversion','Digital journeys designed around a measurable action'],['Reach','Campaign and content systems built to travel'],['Recall','Distinctive assets that make the brand easier to recognise'],['Velocity','A usable system that makes future production faster']]
const metrics=[['+42%','Qualified enquiries','Illustrative case metric'],['2.8×','Campaign reach','Illustrative case metric'],['+31%','Landing page conversion','Illustrative case metric'],['68%','Repeat / referral work','Illustrative studio metric']]
export default function ServicesPage(){return <main className="innerPage servicesPage"><SiteHeader/><section className="pageHero"><span>Programs / Capabilities</span><h1>Everything the<br/><i>idea needs.</i></h1><p>One studio, multiple disciplines. We assemble the right mix of strategy, design and production around the problem instead of forcing every project through the same process.</p></section><section className="serviceArchive"><div className="serviceArchiveList">{services.map(([n,t,d])=><article id={t.split(' ')[0].toLowerCase()} key={t}><span>{n}</span><div><h2>{t}</h2><p>{d}</p></div><b>↗</b></article>)}</div></section><section className="pricingSection"><div className="sectionIntro"><span>Investment / Indicative pricing</span><h2>No packages.<br/><i>Just a useful range.</i></h2></div><p className="pricingLead">These are working engagement bands, not fixed packages. Final pricing depends on scope, timeline, number of touchpoints and production requirements, and is confirmed after a brief.</p><div className="pricingGrid">{pricing.map(([n,t,price,d])=><article key={n}><small>{n} / INDICATIVE</small><h3>{t}</h3><strong className="priceBand">{price}</strong><p>{d}</p><Link href="/contact">Discuss scope <ArrowUpRight size={15}/></Link></article>)}</div></section><section className="outcomesSection"><div className="sectionIntro"><span>Growth / Outcomes</span><h2>Measure what<br/><i>actually changes.</i></h2></div><p className="outcomeLead">The metric layer is deliberately built into the site so final case-study evidence can drop in later. The sample figures below are temporary editorial placeholders, not claimed results.</p><div className="metricGrid">{metrics.map(([n,t,s])=><article key={t}><strong>{n}</strong><b>{t}</b><span>{s}</span></article>)}</div><div className="outcomeGrid">{outcomes.map(([n,d])=><article key={n}><strong>{n}</strong><span>{d}</span></article>)}</div></section><section className="darkStatement"><span>Strategy / Design / Production</span><h2>Bring the messy part.<br/><i>We’ll shape it.</i></h2><Link href="/contact">Start a project <ArrowUpRight size={16}/></Link></section><footer><div className="footerBrand"><BrandLogo/></div><Link href="/projects">View the work ↗</Link><Link href="/about">Meet the studio ↗</Link><span>Patna, India</span></footer></main>}
