import Link from 'next/link'
import {ArrowUpRight} from 'lucide-react'
import BrandLogo from '../components/BrandLogo'
import SiteHeader from '../components/SiteHeader'
const values=[['01','Clarity','Find the idea underneath the brief before deciding how it should look.'],['02','Character','Make the work recognisable enough to belong to a brand and unexpected enough to be remembered.'],['03','Collaboration','The best work comes from a close exchange between people, not a handoff.'],['04','Craft','Every frame, letter, transition and detail matters when the work has to live in the real world.']]
const proof=[['500+','Projects / cumulative practice'],['6+','Years across design, film and photography'],['01','Independent studio / Patna, India'],['∞','Disciplines assembled around the problem']]
const recognition=[['MTV India','Featured creative work'],['ELLE India','Photograph published in print and digital'],['India / Worldwide','Independent practice with remote collaboration']]
const clientNotes=[['01','Brand clarity','“The work gave the brand a much clearer point of view. We finally had a system we could use beyond the launch.”'],['02','Digital experience','“It stopped feeling like a collection of pages and started feeling like one complete brand.”'],['03','Creative partnership','“The strongest part was having strategy, design and making handled as one conversation.”']]
export default function AboutPage(){return <main className="innerPage aboutPage"><SiteHeader/><section className="pageHero"><span>Studio / The Minimical &amp; Co.</span><h1>A creative practice<br/><i>built around ideas.</i></h1><p>Minimical is an independent creative studio from Patna, India. We work across brand identity, digital design, motion, photography and film to make ideas clear, memorable and visible.</p></section><section className="aboutStatement"><div><span>Who we are</span><h2>Strategy, design and production in <i>one practice.</i></h2></div><p>We move between disciplines because modern brands rarely live in one medium. A brand can begin with a thought, become a visual system, turn into a website and end up as a film. The idea should remain recognisable through all of it.</p></section><section className="proofSection"><div className="sectionIntro"><span>Practice / Proof</span><h2>Small studio.<br/><i>Wide range.</i></h2></div><div className="proofGrid">{proof.map(([n,t])=><article key={n}><strong>{n}</strong><span>{t}</span></article>)}</div></section><section className="recognitionSection"><div className="sectionIntro"><span>Recognition / Features</span><h2>Work that has<br/><i>left the room.</i></h2></div><div className="recognitionGrid">{recognition.map(([n,t])=><article key={n}><span>↗</span><strong>{n}</strong><p>{t}</p></article>)}</div></section><section><div className="sectionIntro"><span>Our Values</span><h2>The principles<br/><i>behind the work.</i></h2></div><div className="processGrid">{values.map(([n,t,d])=><article key={n}><small>{n}</small><h3>{t}</h3><p>{d}</p></article>)}</div></section><section className="clientNotes"><div className="sectionIntro"><span>Reviews / Testimonials</span><h2>What the work<br/><i>should leave behind.</i></h2></div><div className="clientNoteGrid">{clientNotes.map(([n,t,d])=><article key={n}><small>{n} / Illustrative client note</small><h3>{t}</h3><p>{d}</p></article>)}</div></section><section className="darkStatement"><span>Independent / India</span><h2>Ideas first.<br/><i>Everything else follows.</i></h2><p>Patna, Bihar, India · Working worldwide</p><Link href="/contact">Bring us the hard part <ArrowUpRight size={16}/></Link></section><footer><div className="footerBrand"><BrandLogo/></div><Link href="/projects">View the work ↗</Link><Link href="/contact">Start a project ↗</Link><span>Patna, India</span></footer></main>}
