'use client'
import {useState} from 'react'
import {ArrowUpRight,Menu,Plus,X} from 'lucide-react'
import Link from 'next/link'
import BrandLogo from './components/BrandLogo'
import Reveal from './components/Reveal'
const work=[['01','WHIFFF','whifff','Brand identity / Digital','2026','violet'],['02','Enchanted Vows','enchanted-vows','Identity / Film / Photography','2025','paper'],['03','Lucky Paul','lucky-paul','Brand / Photography','2024','ink'],['04','Health Seva','health-seva','Campaign / Communication','2024','blue'],['05','PawPerity','pawperity','Packaging / Brand','2024','sand'],['06','Jaano Junction','jaano-junction','Event / Identity','2023','brick'],['07','Sampann Gurukul','sampann-gurukul','Education / Brand','2023','green'],['08','The Minimical & Co.','minimical','Studio / Digital','2026','violet'],['09','drop.minimical.online','drop','Internal tool / Digital product','2026','violet']]
const collaborators=[['WHIFFF','Fragrance / Brand','/projects/whifff'],['Enchanted Vows','Wedding / Culture','/projects/enchanted-vows'],['Lucky Paul Photography','Photography','/projects/lucky-paul'],['Health Seva','Healthcare','/projects/health-seva'],['PawPerity','Consumer / Packaging','/projects/pawperity'],['Jaano Junction','Culture / Event','/projects/jaano-junction'],['Sampann Gurukul','Education','/projects/sampann-gurukul'],['Minimical Studio','Production / Creative','/projects/minimical'],['drop.minimical.online','Internal product','/projects/drop']]
const programs=[['01','Brand','Strategy, positioning, naming, identity and systems.'],['02','Digital','Websites, products, campaigns and digital experiences.'],['03','Campaigns','Ideas, art direction, content and launch systems.'],['04','Production','Photography, film, motion, editing and post.']]
const faqs=[['What does Minimical do?','We build brands, digital experiences, campaigns and visual content from strategy through production.'],['Do you work with existing brands?','Yes. We can enter at strategy, identity, digital, campaign or production level depending on the problem.'],['Can you handle a project end to end?','Yes. A single engagement can move from positioning and identity through website, content, film and launch.'],['Where are you based?','Patna, India, working with clients and collaborators across India and internationally.']]
function ProjectVisual({tone,name,large=false}:{tone:string,name:string,large?:boolean}){return <div className={`projectVisual ${tone} ${large?'large':''}`} aria-hidden="true"><div className="visualGlow"/><span className="visualMeta">THE MINIMICAL &amp; CO. / {name}</span><div className="visualFrame"><i/><i/><i/><i/></div><strong>{name.slice(0,2).toUpperCase()}</strong><small>IMAGE PLACEHOLDER / REPLACE WITH {name.toUpperCase()}.JPG</small></div>}
export default function Home(){const[menu,setMenu]=useState(false);const[faq,setFaq]=useState<number|null>(null);return <main className="studioPage"><header className="studioHeader"><Link href="/" className="studioLogo" aria-label="The Minimical & Co. home"><BrandLogo/></Link><nav className="studioNav"><Link href="/projects">Work</Link><Link href="/about">Studio</Link><Link href="/services">Programs</Link><Link href="/contact">Contact</Link></nav><div className="studioHeaderRight"><Link className="startLink" href="/contact">Start a project <ArrowUpRight size={14}/></Link><button className="mobileTrigger" onClick={()=>setMenu(!menu)} aria-label={menu?'Close menu':'Open menu'}>{menu?<X size={20}/>:<Menu size={20}/>}</button></div></header>{menu&&<nav className="mobileNav"><Link href="/projects" onClick={()=>setMenu(false)}>Work</Link><Link href="/about" onClick={()=>setMenu(false)}>Studio</Link><Link href="/services" onClick={()=>setMenu(false)}>Programs</Link><Link href="/contact" onClick={()=>setMenu(false)}>Contact</Link></nav>}
<section className="studioHero" id="top"><div className="heroTopline"><span>Independent creative studio</span><span>Patna / India</span><span>2026</span></div><div className="heroEditorial"><div className="heroEditorialMain"><p className="eyebrow">Strategy / Identity / Digital / Production</p><h1>We build brands<br/>people can <em>feel.</em></h1><p className="heroDescription">Minimical is an independent creative studio for ambitious ideas, from the first strategic question to the final piece of communication.</p><div className="heroActions"><Link href="/projects">Enter the work <ArrowUpRight size={15}/></Link><Link href="/about">Meet the studio <ArrowUpRight size={15}/></Link></div></div></div><div className="heroManifesto"><span>STRATEGY</span><i>×</i><span>DESIGN</span><i>×</i><span>MAKING</span><i>×</i><span>IMPACT</span><span className="heroManifestoNote">09 selected projects ↓</span></div><div className="heroBottom"><span>Independent / 2026</span><Link href="/projects">View archive ↗</Link></div></section>
<section className="studioStatement" id="studio"><div className="sectionLabel"><span>02 / Studio</span><Link href="/about">About the studio ↗</Link></div><div className="statementGrid"><h2>Ideas become stronger when strategy, design and making stay <em>close.</em></h2><div><p>We are a small independent studio working across brand, digital, campaigns and production.</p><p>The studio model keeps the people thinking about the problem close to the people making the answer.</p><Link className="inlineLink" href="/about">Meet the studio <ArrowUpRight size={15}/></Link></div></div></section>
<section className="workSection" id="work"><div className="sectionLabel"><span>03 / Work</span><Link href="/projects">View all projects <ArrowUpRight size={15}/></Link></div><div className="workLead"><h2>Selected work</h2><p>Identity systems, digital experiences, campaigns and production across culture, commerce and people.</p></div><div className="workMosaic">{work.map(([n,name,slug,discipline,year,tone],i)=><Reveal key={slug}><Link href={`/projects/${slug}`} className={`mosaicItem ${i===0?'wide':''}`}><ProjectVisual tone={tone} name={name}/><div className="mosaicCaption"><span>{n}</span><div><strong>{name}</strong><small>{discipline}</small></div><span>{year}</span><ArrowUpRight size={16}/></div></Link></Reveal>)}</div></section>
<section className="collabSection"><div className="sectionLabel"><span>04 / Collaborations</span><span>Selected brands &amp; collaborators</span></div><div className="collabIntro"><h2>Built with brands that wanted something <em>distinct.</em></h2><p>A working selection of identities, campaigns, digital experiences and production partnerships. The visual marks below are intentionally typographic placeholders and can be replaced with supplied logo artwork later.</p></div><div className="brandWall">{collaborators.map(([name,discipline,href])=><Link href={href} key={name}><div><strong>{name}</strong><small>{discipline}</small></div></Link>)}</div></section>
<section className="programSection" id="programs"><div className="sectionLabel"><span>05 / Programs</span><Link href="/services">Capabilities / Investment ↗</Link></div><div className="programIntro"><h2>Bring us the<br/>problem, not<br/>the <em>format.</em></h2><p>Sometimes the answer is a new identity. Sometimes it is a website, campaign, film or a better way of saying what already exists.</p></div><div className="programList">{programs.map(([n,t,d])=><Link href={`/services/category/${t.toLowerCase()}`} key={n}><span>{n}</span><strong>{t}</strong><p>{d}</p><ArrowUpRight size={17}/></Link>)}</div></section>
<section className="principlesSection"><div className="sectionLabel"><span>06 / Point of view</span><span>How we work</span></div><h2>Good work starts before the <em>design.</em></h2><div className="principleList"><article><span>01</span><strong>Start with the problem.</strong><p>A visual answer is useful only when the question underneath it is clear.</p></article><article><span>02</span><strong>Keep the distance short.</strong><p>Strategy, design and production stay close, with fewer handoffs between thinking and making.</p></article><article><span>03</span><strong>Make it live.</strong><p>The work has to survive beyond the presentation deck, across real touchpoints and real audiences.</p></article></div></section>
<section className="faqSection"><div><div className="sectionLabel"><span>07 / Questions</span><span>Before we begin</span></div><h2>Useful<br/>answers.</h2></div><div className="faqList">{faqs.map(([q,a],i)=><div className="faqRow" key={q}><button onClick={()=>setFaq(faq===i?null:i)} aria-expanded={faq===i}><span>{q}</span>{faq===i?<X size={17}/>:<Plus size={17}/>}</button>{faq===i&&<p>{a}</p>}</div>)}</div></section>
<section className="contactSection" id="contact"><div className="contactTop"><span>08 / Contact</span><span>Patna / India / Worldwide</span></div><div className="contactBody"><div><p>Bring us the hard part.</p><h2>Let’s make<br/>it <em>real.</em></h2></div><Link href="/contact">Start a project <ArrowUpRight size={20}/></Link></div></section><footer className="studioFooter"><div className="footerBrand"><BrandLogo/></div><div><span>Studio</span><p>Independent creative studio<br/>Patna, Bihar, India</p></div><div><span>Navigate</span><Link href="/projects">Work</Link><Link href="/about">Studio</Link><Link href="/services">Programs</Link><Link href="/contact">Contact</Link></div><div><span>Connect</span><a href="https://www.instagram.com/theminimical/" target="_blank" rel="noreferrer">Instagram ↗</a><a href="https://www.linkedin.com/company/theminimical/" target="_blank" rel="noreferrer">LinkedIn ↗</a></div><small>© 2026 The Minimical &amp; Co.</small></footer></main>}
