import Link from 'next/link'
import {notFound} from 'next/navigation'
import {ArrowUpRight} from 'lucide-react'
import SiteHeader from '../../components/SiteHeader'
import BrandLogo from '../../components/BrandLogo'
import {getService,services,categories} from '../data'

const serviceWork:{[key:string]:[string,string,string][]}={'brand-strategy':[['WHIFFF','Positioning / Brand strategy','/projects/whifff'],['Lucky Paul Photography','Brand strategy / Photography','/projects/lucky-paul']],'brand-identity':[['WHIFFF','Identity / Digital','/projects/whifff'],['PawPerity','Packaging / Identity','/projects/pawperity']],'web-design':[['WHIFFF','Digital / Brand','/projects/whifff'],['The Minimical & Co.','Studio website','/projects/minimical']],'digital-experiences':[['The Minimical & Co.','Digital experience','/projects/minimical'],['Enchanted Vows','Brand / Digital','/projects/enchanted-vows']],'campaign-strategy':[['Health Seva','Campaign / Communication','/projects/health-seva'],['Jaano Junction','Event / Campaign','/projects/jaano-junction']],'content-campaigns':[['Health Seva','Content / Campaign','/projects/health-seva'],['PawPerity','Content / Brand','/projects/pawperity']],'motion-film':[['Enchanted Vows','Film / Identity','/projects/enchanted-vows'],['WHIFFF','Motion / Brand world','/projects/whifff']],'photography':[['Enchanted Vows','Photography / Film','/projects/enchanted-vows'],['Lucky Paul Photography','Photography / Brand','/projects/lucky-paul']]}
const process=[['Discovery','Understand the brief, audience, constraints and opportunity.'],['Direction','Establish the creative route and decision framework before making expands.'],['Production','Design, shoot, animate, write, build and refine the selected scope.'],['Handoff','Deliver the system, files, guidance and launch support required for use.']]
export function generateStaticParams(){return services.map(s=>({slug:s.slug}))}
export default async function ServicePage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const s=getService(slug);if(!s)notFound();const related=services.filter(x=>x.category===s.category&&x.slug!==s.slug);const category=categories.find(c=>c.name===s.category);const work=serviceWork[s.slug]||[];return <main className="serviceDetail innerPage"><SiteHeader/>
<section className="serviceHero"><div className="serviceKicker"><span>{s.category} / Specialist service</span><div><Link href={`/services/category/${category?.slug}`}>Back to {s.category} ↗</Link><Link href="/services">All programs ↗</Link></div></div><h1>{s.name}<br/><i>{s.tagline}</i></h1><p>{s.description}</p><div className="serviceHeroMeta"><span>Typical fee<strong>{s.fee}</strong></span><span>Format<strong>Tailored scope</strong></span><Link href={`/contact?service=${s.slug}`}>Start an enquiry <ArrowUpRight size={16}/></Link></div></section>
<section className="serviceSplit"><div><span>01 / Scope</span><h2>What this<br/><i>service covers.</i></h2><p className="sectionBodyCopy">The exact scope is shaped around the problem. These are the working components available for this engagement, not a rigid package.</p></div><div className="scopeList">{s.scope.map((x,i)=><article key={x}><small>{String(i+1).padStart(2,'0')}</small><p>{x}</p></article>)}</div></section>
<section className="serviceProcess"><div className="sectionIntro"><span>02 / Process</span><h2>From brief<br/><i>to useful.</i></h2></div><div className="serviceProcessGrid">{process.map(([title,text],i)=><article key={title}><small>{String(i+1).padStart(2,'0')}</small><strong>{title}</strong><p>{text}</p></article>)}</div></section>
<section className="serviceWork"><div className="sectionIntro"><span>03 / Relevant work</span><h2>Where this<br/><i>shows up.</i></h2></div><div className="serviceWorkGrid">{work.map(([name,type,href])=><Link href={href} key={name}><span>PROJECT</span><strong>{name}</strong><small>{type}</small><ArrowUpRight size={18}/></Link>)}</div></section>
<section className="deliverableSection"><div className="sectionIntro"><span>04 / Outputs</span><h2>Designed to<br/><i>be used.</i></h2></div><div className="deliverableGrid">{s.deliverables.map((x,i)=><article key={x}><span>{String(i+1).padStart(2,'0')}</span><strong>{x}</strong></article>)}</div></section>
<section className="serviceMetrics"><div className="sectionIntro"><span>05 / Performance / Editorial placeholders</span><h2>What success<br/><i>could look like.</i></h2><p>Temporary sample figures complete the information architecture. Replace them with approved case evidence when supplied.</p></div><div className="metricGrid">{s.metrics.map(([n,t])=><article key={t}><strong>{n}</strong><b>{t}</b><span>Illustrative placeholder</span></article>)}</div></section>
<section className="serviceReviews"><div className="sectionIntro"><span>06 / Client voice / Editorial placeholders</span><h2>What clients<br/><i>remember.</i></h2></div><div className="reviewGrid">{s.reviews.map(([who,q])=><article key={who}><span>Illustrative review</span><p>{q}</p><small>{who}</small></article>)}</div></section>
<section className="serviceEnquiry"><div><span>07 / Project enquiry</span><h2>Let's talk about<br/><i>{s.name.toLowerCase()}.</i></h2><p>Send the context, ambition, timeline and investment range. We will reply with the most useful next step.</p><div className="categoryContactDetails"><span>contact@minimical.online</span><span>+91 87095 39814</span><span>Patna / India / Worldwide</span></div></div><form action="mailto:contact@minimical.online" method="post" encType="text/plain"><input name="name" placeholder="Name" required/><input name="email" type="email" placeholder="Email" required/><input name="company" placeholder="Company / Brand"/><input name="timeline" placeholder="Timeline / launch date"/><input name="budget" placeholder={`Budget / ${s.fee}`}/><textarea name="brief" placeholder={`Tell us about your ${s.name.toLowerCase()} requirement`} rows={6} required/><button type="submit">Send project enquiry <ArrowUpRight size={16}/></button></form></section>
<section className="relatedServices"><div className="sectionIntro"><span>08 / Continue</span><h2>Keep the<br/><i>system connected.</i></h2></div><div>{related.map(x=><Link href={`/services/${x.slug}`} key={x.slug}><span>{x.category}</span><strong>{x.name}</strong><ArrowUpRight size={17}/></Link>)}</div><div className="serviceNavLinks"><Link href={`/services/category/${category?.slug}`}>← {s.category} program</Link><Link href="/services">All programs ↗</Link></div></section>
<footer><div className="footerBrand"><BrandLogo/></div><Link href="/projects">Work ↗</Link><Link href="/about">Studio ↗</Link><Link href="/services">Programs ↗</Link><Link href="/contact">Contact ↗</Link><span>Patna / India / Worldwide</span></footer></main>}